services:
  deeplearning:
    platform: linux/amd64
    image: graphdl:1.0.0
    user: "mattfeng"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - ./:/app
